Protect GemVersionCollection from exploding due to [nil,nil,nil] being un-marshalled from specs.4.8.gz
I've noticed on Rubygems 1.7.2 on FreeBSD when Geminabox reindexes the gems after receiving a new gem that an Internal Error is raised due to a NoMethodError - undefined method `<=>' for nil:NilClass when calling sort!

As far as I could tell this was due to the presence of [nil,nil,nil] in the specs un-marshalled data.